services:
  discord-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - db:/app/data
    restart: unless-stopped
    depends_on:
      - damru-pool
    environment:
      DAMRU_API_URL: http://damru-pool:5000

  damru-redroid:
    image: damru-redroid:latest
    privileged: true
    volumes:
      - damru-data:/data
      - /dev/binderfs:/dev/binderfs
    environment:
      - androidboot.redroid_width=1080
      - androidboot.redroid_height=2400
      - androidboot.redroid_dpi=480
    restart: unless-stopped
    ports:
      - "5555:5555"

  damru-pool:
    build:
      context: ./damru-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      REDROID_CPUS: "2.0"
      REDROID_MEMORY: "2g"
      NUM_DEVICES: 2
      REDROID_HOST: damru-redroid
      REDROID_PORT: 5555
    depends_on:
      - damru-redroid
    restart: unless-stopped
    volumes:
      - damru-pool-data:/home/damru
      - db:/app/data


volumes:
  db:
  damru-data:
  damru-pool-data: